### PR TITLE
fix: add `deno install` root to path

### LINKED ISSUE #5: Add bin directory to the path
Previously `.deno/bin` was added to the path when using denolib/setup-deno.
https://github.com/denolib/setup-deno/blob/3c5f954c869f1b0d106e129797480905587250f5/src/installer.ts#L80
Now this is no longer the case.

This is a shame because if one installs tools with `deno install` then they are not found.

### PR DESCRIPTION
**Pull request by satyarohith**
cc @lucacasonato

Closes #5

### CODE REVIEW

File: src/install.js [hunk 1]
```diff
@@ -31,8 +33,11 @@ async function install(version) {
     "deno",
     version.isCanary ? `0.0.0-${version.version}` : version.version,
   );
-  core.info(`Cached Deno to ${newCachedPath}.`);
   core.addPath(newCachedPath);
+  core.info(`Cached Deno to ${newCachedPath}.`);
```
Comment (satyarohith) [inline src/install.js:37]:
```suggestion
  core.info(`Cached Deno to ${newCachedPath}.`);
  core.addPath(newCachedPath);
```

**Review by kt3k — APPROVED** [review]
LGTM 👍
